In [1]:
import matplotlib.pyplot as plt
import math
import numpy as np

In [21]:
def r(u, lam):
    r1 = u[0] + 2*u[0]**3 - u[1]**2 - 2*lam
    r2 = 3*u[1] - 2*u[0]*u[1] - lam
    return np.array([r1, r2])
def K(u):
    K11 = (1 + 6*u[0]**2)
    K12 = (-2*u[1])
    K21 = K12
    K22 = 3 - u[0]
    return np.array([[K11, K12], [K21, K22]])


In [22]:
u0 = [0,0]
r_0 = r(u0, 0.1)
K_0 = K(u0)
np.matmul(r_0, K_0)

array([-0.2, -0.3])

In [26]:
# Getting different result than textbook for some reason
max_iterations = 5
u0 = [0.8, 0.8]
lam = 1
uk = u0
for i in range(max_iterations):
    ukpt = uk - np.dot(np.linalg.inv(K(uk)), r(uk, lam))
    uk = ukpt
    print(ukpt)

r(uk, lam)

[0.99821958 0.88961424]
[0.97953506 0.92656832]
[0.9858338  0.94991927]
[0.99023208 0.96557004]
[0.99323303 0.97619912]


array([-5.94169505e-05, -1.05890484e-02])

In [27]:
# Approximation same solution, even though textbook says it shouldnt

max_iterations = 5
u0 = [0.8, 0.8]
lam = 1
uk = u0
for i in range(max_iterations):
    ukpt = uk - np.dot(np.linalg.inv(K(uk)), r(uk, lam))
    uk = ukpt
    print(ukpt)

r(uk, lam)

[0.99821958 0.88961424]
[0.97953506 0.92656832]
[0.9858338  0.94991927]
[0.99023208 0.96557004]
[0.99323303 0.97619912]


array([-5.94169505e-05, -1.05890484e-02])

In [30]:
# Approximation same solution, even though textbook says it shouldnt

max_iterations = 30
u0 = [1.18, 1.58]
lam = 1
uk = u0
for i in range(max_iterations):
    ukpt = uk - np.dot(np.linalg.inv(K(uk)), r(uk, lam))
    uk = ukpt
    print(ukpt)

[1.18281551 1.57873462]
[1.1821345  1.57672573]
[1.18108289 1.57359588]
[1.17945497 1.56874866]
[1.17695866 1.56131059]
[1.17318557 1.55005596]
[1.16760464 1.53338058]
[1.15960616 1.50941926]
[1.14864081 1.47643901]
[1.13447429 1.43357708]
[1.11748004 1.3817184 ]
[1.09876001 1.32392281]
[1.0798991  1.26482331]
[1.06243651 1.20915905]
[1.04740431 1.16037595]
[1.0351921  1.12006867]
[1.02569179 1.08825103]
[1.01852883 1.06397772]
[1.01324655 1.04591556]
[1.00941141 1.03271388]
[1.00665721 1.02318711]
[1.00469439 1.01637412]
[1.00330305 1.01153283]
[1.00232051 1.00810803]
[1.00162847 1.00569289]
[1.00114196 1.00399352]
[1.00080036 1.00279964]
[1.00056074 1.0019618 ]
[1.00039276 1.00137426]
[1.00027505 1.00096248]


-2.6999999999999996e-05